### ISSUE TITLE
How to use this on typescript?

### ISSUE THREAD

**Issue by naonvl** [bertyhell/video-to-frames#2]
hey i found that this is what i need, can this be used on typescript?

Also i got this error after tying to import it to angular

```
Type 'CanvasRenderingContext2D | null' is not assignable to type 'CanvasRenderingContext2D'.
  Type 'null' is not assignable to type 'CanvasRenderingContext2D'.
```

**Comment by bertyhell** [comment]
sorry i only saw your remark now.

You would probably need to make sure the canvas is fetched correctly and otherwise throw an error:
```typescript
let context: CanvasRenderingContext2D | null = canvas.getContext('2d');
if (!context) {
  throw new Error('Failed to fetch canvas from created canvas: ', canvas);
}
```

**Comment by naonvl** [comment]
I fixed it but i forgot how, i didn't change that line. But i'll added it to my code. just in case
