### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by naonvl** [bertyhell/video-to-frames#3]
Thanks to your repo, I finish my task to render frames from user video. I need to change a couple lines of you code to make it work on angular, or any Typescript programs. I'd like to make a PR for `videotoframe.ts` also I'd like to add an instruction how to use that on others project. How could I contribute? what's the rule?

**Comment by bertyhell** [comment]
Any contributions would be greatly appreciated. As long as the existing functionality keeps working as is and you only add functionality, there should not be any problems with getting your PR merged.

This code is already quite old, and i'm not personally using the code anymore, so any improvements will get merged.

**Comment by naonvl** [comment]
I was searching about webcodecs, and i found yours, does this also using webcodecs?

Anyway, yours works better than using solution that i found on SO. thanks, I'll make a PR when i got time

**Comment by bertyhell** [comment]
> I was searching about webcodecs, and i found yours, does this also using webcodecs?

Yes it uses the browser video object to decode the video files.
